# Generated by Django 5.1.3 on 2024-12-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
